### ISSUE TITLE
NameError: name 'camera_info' is not defined

### ISSUE THREAD

**Issue by wgerlach** [tmilliman/phenocam_download_script#3]
Line 107 references camera_info which does not seem to be defined anywhere.

**Comment by tmilliman** [comment]
Reference removed.  Thanks for the catch.  Dealing with bug in API which complicates pulling camera info.

**Comment by wgerlach** [comment]
ah ,there is more, sys.exit(0) in line 125 and a check if day is defined seems to be missing
